MBL-224 cross server traffic
spatialos/UnrealGDKTestGyms pull request #341
Opened 2021-04-06 09:43 UTC by joanxie878

What this PR do?

We want to add means to generate cross server so that we can send data from non-authority server to other server, we use the worker flag "cross_server_size" to set the size of the array data we need to send, and we use the worker flag "cross_server_frequency" to determine how many seconds we send data once.

Test Link:
https://buildkite.com/improbable/unrealgdk-nfr/builds/4255 (2_1 zone for 1size*5frequency)

Test Result:
![image](https://user-images.githubusercontent.com/78347372/113691872-7e9d5880-96ff-11eb-9620-29800d4e57db.png)

2021-04-14 09:52 UTC, jayprobable requested changes

2021-04-14 09:52 UTC, jayprobable commented on Game/Source/GDKTestGyms/AUptimeGameMode.cpp
> +		Comp->ClientSetBlackboardAILocations(CrossServerRunPoints[i]);
Why do the cross server beacons have run points?

2021-04-14 09:52 UTC, jayprobable commented on Game/Source/GDKTestGyms/AUptimeGameMode.h
> +	TArray<FBlackboardValues> CrossServerRunPoints;
We should be able to remove these.. the beacons should be stationary

2021-04-14 09:52 UTC, jayprobable commented on Game/Source/GDKTestGyms/UptimeCrossServerBeacon.h
> +	public ACharacter
This shouldn't be a character it just needs to derive from actor

2021-04-15 02:42 UTC, jeffxu-improbable commented on Game/Source/GDKTestGyms/UptimeCrossServerBeacon.h
> +	public AActor
`class AUptimeCrossServerBeacon : public AActor`
I'd like to put these in the same line instead.

2021-04-15 02:45 UTC, jeffxu-improbable approved these changes
Other than a few minor code style issues, everything else is find now.

2021-04-16 10:34 UTC, jayprobable approved these changes

2021-04-16 10:42 UTC, merged